bugfix py2 ustr()
